services:
  automaton.plugin.server:
    class: Automaton\Server\ServerPlugin
  automaton.event_subscriber.server:
    class: Automaton\Server\ServerPluginEventSubscriber
    arguments: [@automaton.plugin.server, @event_dispatcher]
    tags:
      - { name: kernel.event_subscriber, event: automaton.task_command.configure }
      - { name: kernel.event_subscriber, event: automaton.task.pre_run }
      - { name: kernel.event_subscriber, event: automaton.task.invoke }
