services:
  deployer.plugin.runner:
    class: Deployer\Runner\RunnerPlugin
  deployer.runner:
    class: Deployer\Runner\Runner
  deployer.event_subscriber.runner:
    class: Deployer\Runner\RunnerPluginEventSubscriber
    arguments: [@deployer.plugin.runner]
    tags:
      - { name: kernel.event_subscriber, event: deployer.task_command.configure }
      - { name: kernel.event_subscriber, event: deployer.runner.pre_run }
      - { name: kernel.event_subscriber, event: deployer.runner.post_run }
