services:
  deployer.plugin.server:
    class: Deployer\Server\ServerPlugin
    arguments:
      - {ssh: Deployer\Server\SshServer}
  deployer.event_subscriber.server:
    class: Deployer\Server\ServerPluginEventSubscriber
    arguments: [@deployer.plugin.server]
    tags:
      - { name: kernel.event_subscriber, event: deployer.task_command.configure }
      - { name: kernel.event_subscriber, event: deployer.runner.pre_run }
      - { name: kernel.event_subscriber, event: deployer.runner.post_run }
